name: ai_pocket_tools
description: AI Pocket Tools
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  bloc: ^8.1.2
  dart_openai: ^5.0.0
  ffmpeg_kit_flutter_audio: ^6.0.3
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.10
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18+3
  flutter_riverpod: ^2.4.9
  flutter_speed_dial: ^7.0.0
  fpdart: ^1.1.0
  http: ^1.1.2
  intl: ^0.18.1
  langchain: ^0.3.1+1
  langchain_ollama: ^0.0.2+1
  langchain_openai: ^0.3.1+1
  lazy_load_indexed_stack: ^1.0.1
  mime: ^1.0.4
  money2: ^4.0.0
  ollama_dart: ^0.0.2
  path: ^1.8.3
  path_provider: ^2.1.2
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  settings_ui: ^2.0.2
  share_handler: ^0.0.20
  share_plus: ^7.2.1
  supabase_flutter: ^2.1.0
  tokencost: ^0.0.5
  uuid: ^4.2.2
  video_player: ^2.8.2

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  riverpod_generator: ^2.3.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
