name: ai_pocket_tools
description: AI Pocket Tools
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  bloc: ^8.1.2
  dart_openai: ^5.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  fpdart: ^1.1.0
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  share_handler: ^0.0.20
  uuid: ^4.2.2

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  riverpod_generator: ^2.3.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
